### ISSUE TITLE
[maintenance] Use groupinstalls for essential packages

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/deepin#7]
It would be better to implement group installs for this because it would make maintaining this image a bit easier: We'd just install some groups, and not worry about every single package being installed

**Comment by castrojo** [comment]
group installs aren't supported in rpm-ostree but this is the issue to track:

- https://github.com/coreos/rpm-ostree/issues/2082

**Comment by tulilirockz** [comment]
Yup! For now we could implement this with a workaround e.g. the one used in the [budgie](github.com/ublue-os/budgie) image
